### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by 0n1cOn3**
Missing "t" added for not found.

### CODE REVIEW

**Comment by RaulXH** [comment]
Hello, what is your architecture? it's I686.To add it.  thanks

**Comment by 0n1cOn3** [comment]
Hello.

Nowadays, aarch64 

And Grammar fixes has nothing todo with arch 😵‍💫

**Comment by RaulXH** [comment]
Yes of course.  I was referring to the dpkg package architecture type.  Since in termux the most common are arm and aarch64.  Because of the version of ruby ​​that metasploit uses.

It still uses version 2.7.2. Thanks bro for the error.

**Comment by 0n1cOn3** [comment]
Hehe, mee too ;-) and i386 is not used in termux. just arm/arm64. And i386 is x86 which is not arm at all :-P

**Pull request closed without merging**
